### ISSUE TITLE
npm run dist【dist_linux】出错

### ISSUE THREAD

**Issue by sunjiaxing1992** [hechuanhua/blog#8]
我是node初学，问一下这是什么原因，怎么解决呢？

```
false 'production'
/blog/src/server.js:11
import React, { Component } from 'react'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/blog/app.js:41:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

**Comment by hechuanhua** [comment]
@sunjiaxing1992  你把config/index.js 下面的 isDev : !isDev 改为  isDev : isDev就可以了，
上次改动比较大，估计很多地方现在都有问题，本地的改好了我再更新下
